version: 2.1
orbs:
  node: circleci/node@5.1.1

jobs:
  test:
    docker:
      - image: "cimg/node:20"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Exécuter les tests unitaires
          command: npm run test
      - run:
          name: Exécuter les tests d'API
          command: npm run test:api
      - store_test_results:
          path: test-results

  build:
    docker:
      - image: "cimg/node:20"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t app:${CIRCLE_SHA1} .

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test