import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layouts/header";
import { AuthProvider } from './providers'
import Image from "next/image";
import PageTransition from '@/components/transitions/PageTransition';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="bg-influenca-black relative">
        <Image src="/logo/logo.png" alt="logo" width={72} height={72} className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 -z-10" priority/>
        <AuthProvider>
          <Header />
          <main>
            <PageTransition>
              {children}
            </PageTransition>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
